# comparing_nets_plots.py
'''
Make some plots to compare string chemistry networks to the E. coli and yeast
metabolic networks using the data generated by comparing_nets_data.py
'''

import pandas as pd
from matplotlib import pyplot as plt
from matplotlib.gridspec import GridSpec
import sys

def plot_scn(axes, data, x_col):
    '''
    Plot the mean frequencies of either degrees or fluxes on a log-log
    scatterplot with errorbars on the points representing the standard 
    deviations of those frequencies
    '''
    axes.scatter(
        data = data, 
        x = x_col, 
        y = 'mean_freq', 
        c = 'blue',
        label = 'String Chemistries'
    )
    axes.errorbar(
        data = data,
        x = x_col,
        y = 'mean_freq',
        yerr = 'std_freq',
        linestyle = 'None',
        c = 'blue',
        label = ''
    )
    return(axes)

def plot_dist(axes, data, x_col, color, label):
    '''
    Plot a distribution of either degrees or fluxes on a log-log scatterplot
    '''
    axes.scatter(
        data = data, 
        x = x_col, 
        y = 'freq', 
        c = color, 
        label = label
    )
    return(axes)

def fix_axes(axes, x_lab, y_lab, panel):
    '''
    Make a set of axes log-scaled with appropriate labels
    '''
    axes.set_xlabel(x_lab)
    axes.set_ylabel(f'Frequency of {y_lab} With {x_lab}')
    axes.set_xscale('log')
    axes.set_yscale('log')
    axes.text(
        # position the letter above the plot on the left side
        -0.11, 1.1, panel, va = 'top', ha = 'right',
        # no idea what this does; got it from StackOverflow
        transform = axes.transAxes,
        # make the letter large and bold
        fontsize = 14, fontweight = 'bold' 
    )
    # make a legend so it's clear which colors represent which thing
    axes.legend()
    return(axes)

# read in files produced by comparing_nets_data.py
scn_deg_dists = pd.read_csv('data/scn_deg_dists.csv')
scn_flux_dists = pd.read_csv('data/scn_flux_dists.csv')
ecoli_deg_dist = pd.read_csv('data/ecoli_deg_dist.csv')
ecoli_flux_dist = pd.read_csv('data/ecoli_flux_dist.csv')
yeast_deg_dist = pd.read_csv('data/yeast_deg_dist.csv')
yeast_flux_dist = pd.read_csv('data/yeast_flux_dist.csv')

# make two subplots so we can have the degree and flux distributions in the
# same figure
fig = plt.figure(figsize = (12,6))
gs = GridSpec(1,2, figure = fig)
deg_ax = fig.add_subplot(gs[0,0])
flux_ax = fig.add_subplot(gs[0,1])

# give each degree distribution a different color since they're all going on
# the same axes
deg_ax = plot_scn(deg_ax, scn_deg_dists, 'degree')
deg_ax = plot_dist(deg_ax, ecoli_deg_dist, 'degree', 'red', 'E. coli')
deg_ax = plot_dist(
    deg_ax, yeast_deg_dist, 'degree', 'green', 'S. cerevisiae'
)
deg_ax = fix_axes(deg_ax, 'Degree', 'Metabolites', 'a')

# now do the same thing with the flux distributions
flux_ax = plot_scn(flux_ax, scn_flux_dists, 'flux')
flux_ax = plot_dist(flux_ax, ecoli_flux_dist, 'flux', 'red', 'E. coli')
flux_ax = plot_dist(flux_ax, yeast_flux_dist, 'flux', 'green', 'S. cerevisiae')
flux_ax = fix_axes(flux_ax, 'Flux', 'Reactions', 'b')
# make sure subplots don't overlap with each other
plt.tight_layout()
plt.savefig('data/deg_flux_dists.png', dpi = 600)
#plt.show()
