# figure_S5_S6.R
# make some plots with the data generated by figure_S5_S6_data.py

suppressMessages(library(tidyverse))

theme_set(theme_bw())

data <- read.csv(
  "data/varied_ab_5_2to5ins_2to10outs_exp.csv", 
  header = F,
  col.names = c("env_comp", "bm_comp", "ratio", "pruned_pct")
) %>%
  mutate(bm_comp = as.factor(bm_comp)) %>%
  mutate(env_comp = as.factor(env_comp))

# show how the percentage of reactions removed by pruning changes as you change
# the number of food sources and the number of biomass precursors
png("data/figure_S5.png", height = 5000, width = 7000, res = 600)
data %>%
  # graph is a bit too busy with all the points on it
  filter(as.numeric(as.character(bm_comp)) < 11) %>%
  group_by(bm_comp, env_comp) %>%
  summarize(
    # get mean and standard deviation
    mean_pruned = mean(pruned_pct),
    stdev = sd(pruned_pct)
  ) %>%
  ggplot(aes(x = bm_comp, y = mean_pruned)) + 
    geom_pointrange(
      aes(ymin = mean_pruned - stdev, ymax = mean_pruned + stdev, col = env_comp),
      position = position_dodge(width = 0.75)
    ) +
    labs(
      x = "Number of Biomass Precursors",
      y = "Percent of Reactions Removed During Pruning",
      col = "Number of Food Sources"
    ) +
    theme(text = element_text(size = 15))
invisible(dev.off())

# show how the ratio of reactions to metabolites changes as you change the
# number of food sources and the number of biomass precursors
png("data/figure_S6.png", height = 5000, width = 7000, res = 600)
data %>%
  # graph is a bit too busy with all the points on it
  filter(as.numeric(as.character(bm_comp)) < 11) %>% 
  group_by(bm_comp, env_comp) %>%
  summarize(
    mean_ratio = mean(ratio),
    stdev = sd(ratio)
  ) %>%
  ggplot(aes(x = bm_comp, y = mean_ratio)) + 
    geom_pointrange(
      aes(ymin = mean_ratio - stdev, ymax = mean_ratio + stdev, col = env_comp),
      position = position_dodge(width = 0.75)
    ) +
    labs(
      x = "Number of Biomass Precursors",
      y = "Number of Reactions / Number of Metabolites in Pruned Network",
      col = "Number of Food Sources"
    ) +
    theme(text = element_text(size = 15))
invisible(dev.off())
