# figure_S2_S3.R
# make some plots with the data generated by figure_S1_S2.py

suppressMessages(library(tidyverse))

theme_set(theme_bw())

data <- read.csv(
  "data/varied_ab_5_2to5ins_2to20outs_exp.csv", 
  header = F,
  col.names = c("env_comp", "bm_comp", "ratio", "pruned_pct")
) %>%
  mutate(bm_comp = as.factor(bm_comp)) %>%
  mutate(env_comp = as.factor(env_comp))

# show how the percentage of reactions removed by pruning changes as you change
# the number of food sources and the number of biomass precursors
png("data/figure_S2.png", height = 500, width = 700)
ggplot(data, aes(x = bm_comp, y = pruned_pct)) + 
  geom_violin(aes(fill = env_comp)) +
  labs(
    x = "Number of Biomass Precursors",
    y = "Percent of Reactions Removed During Pruning",
    col = "Number of Food Sources",
    title = "Number of Biomass Precursors Dictates Proportion of Pruned Reactions"
  )
invisible(dev.off())

# show how the ratio of reactions to metabolites changes as you change the
# number of food sources and the number of biomass precursors
png("data/figure_S3.png", height = 500, width = 700)
ggplot(data, aes(x = bm_comp, y = ratio)) + 
  geom_violin(aes(fill = env_comp)) +
  labs(
    x = "Number of Biomass Precursors",
    y = "Number of Reactions / Number of Metabolites in Pruned Network",
    col = "Number of Food Sources",
    title = "Number of Biomass Precursors Dictates Reaction-to-Metabolite Ratio"
  )
invisible(dev.off())

