---
title: "ggplot Grouped Bar Chart"
author: "Devlin Moyer"
date: "13 11 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
```

Makes a barchart where network size is along the x-axis (so networks are grouped by their size) and the number of times the network was returned as the output from the random pruner is on the y-axis

```{r}
# if the bitstrings are long, sometimes this is necessary
data <- readChar(
    "data/ab_5_2ins_5outs_1of100bitstrings.csv",
    nchars = 3240
  ) %>%
  strsplit("\n") %>%
  as.data.frame(.) %>%
  rename(mess = 1) %>%
  separate(mess, sep = ",", into = c(
    "row", "bitstring", "occurrences", "rxn_count")
  ) %>%
  select(-row) %>%
  mutate(bitstring = as.factor(bitstring)) %>%
  mutate(rxn_count = as.numeric(rxn_count)) %>%
  mutate(occurrences = as.numeric(occurrences))

# trying to filter out the first row was also being weird
data <- data[-1,]
```

```{r fig.width=10}
data <- read.csv(
  "data/abc_5_2ins_5outs_1000reps.csv",
  sep = ",", header = TRUE, row.names = 1, 
  colClasses = c("numeric", "factor", "numeric")
)

ggplot(data, aes(x = rxn_count, y = occurrences)) + 
  geom_bar(position = "dodge", stat = "identity", aes(fill = bitstring)) +
  theme_bw() + theme(legend.position = "none") +
  labs(
    x = "Number of Reactions", 
    y = "Number of Times Network Was Observed", 
    title = "Results of 1000 Random Prunes"
)
```
